apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: report-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasfikurRahaman/expense-tracker-gitops.git
    targetRevision: main
    path: report-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

